[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]  # ステータスラインに色を付ける
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#buffer_idx_mode = 1
  let g:airline#extensions#whitespace#mixed_indent_algo = 1
  let g:airline_theme = 'dark'
  set laststatus=2
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]  # colorscheme
repo = 'tomasr/molokai'

[[plugins]]  # colorscheme
repo = 'altercation/vim-colors-solarized'

[[plugins]]  # 末尾のスペースを削除
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]  # markdownプレビュー
repo = 'kannokanno/previm'
depends = ['open-browser.vim']
hook_add = '''
  nnoremap po :PrevimOpen<CR>
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]  # スクリプト実行
repo = 'thinca/vim-quickrun'
on_source = ['vimproc.vim']
hook_add = '''
  noremap qr :QuickRun<CR>
'''

[[plugins]]  # 構文チェック
repo = 'w0rp/ale'
on_source = ['vim-airline']
hook_add = '''
  let g:ale_python_mypy_options = '--ignore-missing-imports'
  let g:airline#extensions#ale#enabled = 1
  let g:ale_linters = {'tex': [],}
'''

[[plugins]]  # 補完
repo = 'zchee/deoplete-jedi'
depends = ['Shougo/deoplete.nvim']
on_i = 1
on_ft = 'python'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#sources#jedi#server_timeout = 30
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  set completeopt-=preview
'''

[[plugins]]  # go用
repo = 'fatih/vim-go'
on_ft = 'go'
